language: python
sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          python: 2.7
        - os: osx
          language: generic

before_install:
  - curl https://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.6.tgz -o ./spark-2.1.1-bin-hadoop2.6.tgz
  - sudo tar -xf ./spark-2.1.1-bin-hadoop2.6.tgz
  - mkdir -p marvin_data
  - mkdir -p marvin_home
  - export MARVIN_HOME=./marvin_home
  - export MARVIN_DATA_PATH=./marvin_data
  - export SPARK_HOME=./spark-2.1.1-bin-hadoop2.6
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo easy_install pip          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl graphviz  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libsasl2-dev python-pip graphviz -y ; fi
  - sudo pip install --upgrade pip
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install virtualenvwrapper ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install virtualenvwrapper --ignore-installed six       ; fi
  - source virtualenvwrapper.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkvirtualenv marvin-env         ; fi

install:
  - make marvin
  - pip install codecov

script:
  - marvin test
  - codecov

deploy:
  provider: pypi
  user: "takabayashi"
  password:
    secure: siUVUMBLqqP2IihmoG8foGwIz6ne5PzFxYjAGFYGraJWCqrxDyvmQLbJlmNCxl6S7ZSr33ZGmaKshMH8vdDHFkfs0NuxvPzeDLwezd9Z6rPXrddB7oDo9OZfk0oyMfpj0jKJwiCT1gnZdoMceRjRuZII3rgWr9vwNhXu8xT1Vq0ncwZv/A5SS1/uicw8KCECI/zaTW+sDaCax3xIQfb67WeuxxGEHj62spCyGrvqwTOZidFtd14e/7MnA3d6Y84LWUS2YaLxE7awjiH1rR/lV0YOy9Gb8GXBPIUrrRBbeSWc+uiBj7HsSgBRbF2u+nrBTdXlH6eapKAlGyUUHuLCwaG+PIeGkU9G7cH5mBLvbJHejZYl8oyNwfdulmSmvdauMXZJHS37oDmGclLDyNWA+PWZK6Za/dmF5x5Ti+3qXY2GeF1nKxnprJ5BKaegtE0lTz1ATMKi+UpEi6kxAXNKwSK3/XECdOYadz+JW6wHjmjCnQ80m3Uq9oZLQsAi4wUiEn3FtH8rwlwlQZyxOxyzHuFRtq56AUl1bqiGDrIqdrJy6+E3BgwCBL8a8sQq0EfMTN9ciOqsd+9tILBz4ArvurrN2OJ20TRZ2GjRKzUZy+pLRW/VqIFmBPCmnlPh0uR1lfX8+aaFnlch4KTbS7lqCj4cqTtZpcFQLuWiIsW9kXE=
  on:
    branch: master
